export const FRED_SERIES: Record<string, string> = {
  FED_FUNDS_UPPER: "DFEDTARU",
  FED_FUNDS_LOWER: "DFEDTARL",
  US_10Y: "DGS10",
  US_2Y: "DGS2",
  US_30Y: "DGS30",
  CPI: "CPIAUCSL",
  CORE_CPI: "CPILFESL",
  CORE_PCE: "PCEPILFE",
  UNEMPLOYMENT: "UNRATE",
  INITIAL_CLAIMS: "ICSA",
  NFP: "PAYEMS",
  CONSUMER_CONF: "UMCSENT",
  IG_SPREAD: "BAMLC0A0CM",
  HY_SPREAD: "BAMLH0A0HYM2",
  SPREAD_2S10S: "T10Y2Y",
};

export const YFINANCE_TICKERS: Record<string, string> = {
  SP500: "^GSPC",
  DOW: "^DJI",
  NASDAQ: "^IXIC",
  FTSE100: "^FTSE",
  NIKKEI: "^N225",
  VIX: "^VIX",
  OIL_WTI: "CL=F",
  OIL_BRT: "BZ=F",
  GOLD: "GC=F",
  COPPER: "HG=F",
  DXY: "DX-Y.NYB",
};

export const LABEL_MAP: Record<string, string> = {
  SP500: "S&P 500",
  DOW: "Dow Jones",
  NASDAQ: "Nasdaq Composite",
  FTSE100: "FTSE 100",
  NIKKEI: "Nikkei 225",
  VIX: "VIX",
  OIL_WTI: "WTI Crude Oil",
  OIL_BRT: "Brent Crude",
  GOLD: "Gold",
  COPPER: "Copper",
  DXY: "DXY (Dollar Index)",
};

export const CATEGORY_MAP: Record<string, string> = {
  SP500: "Market Indices",
  DOW: "Market Indices",
  NASDAQ: "Market Indices",
  FTSE100: "Market Indices",
  NIKKEI: "Market Indices",
  VIX: "Market Sentiment",
  OIL_WTI: "Prices & Inflation",
  OIL_BRT: "Prices & Inflation",
  GOLD: "Prices & Inflation",
  COPPER: "Prices & Inflation",
  DXY: "Market Sentiment",
};

export const SECTION_ORDER = [
  "Rates & Monetary Policy",
  "Real Economy",
  "Prices & Inflation",
  "Market Sentiment",
  "Market Indices",
];

export const SECTION_ICONS: Record<string, string> = {
  "Rates & Monetary Policy": "\u{1f3e6}",
  "Real Economy": "\u{1f4ca}",
  "Prices & Inflation": "\u{1f4c8}",
  "Market Sentiment": "\u{1f630}",
  "Market Indices": "\u{1f4b9}",
};

export const CORRELATIONS: Record<string, string[]> = {
  FED_FUNDS: ["US_2Y", "US_10Y", "SPREAD_2S10S"],
  US_2Y: ["FED_FUNDS", "US_10Y", "SPREAD_2S10S"],
  US_10Y: ["US_2Y", "US_30Y", "SP500"],
  US_30Y: ["US_10Y", "SPREAD_2S10S", "GOLD"],
  SPREAD_2S10S: ["US_2Y", "US_10Y", "FED_FUNDS"],
  CPI_YOY: ["CORE_CPI_YOY", "OIL_WTI", "FED_FUNDS"],
  CORE_CPI_YOY: ["CPI_YOY", "CORE_PCE_YOY", "FED_FUNDS"],
  CORE_PCE_YOY: ["CPI_YOY", "CORE_CPI_YOY", "FED_FUNDS"],
  UNEMPLOYMENT: ["NFP", "INITIAL_CLAIMS", "CONSUMER_CONF"],
  INITIAL_CLAIMS: ["UNEMPLOYMENT", "NFP", "SP500"],
  NFP: ["UNEMPLOYMENT", "INITIAL_CLAIMS", "SP500"],
  ISM_MFG: ["COPPER", "SP500", "CONSUMER_CONF"],
  CONSUMER_CONF: ["SP500", "UNEMPLOYMENT", "NFP"],
  IG_SPREAD: ["HY_SPREAD", "VIX", "SP500"],
  HY_SPREAD: ["IG_SPREAD", "VIX", "SP500"],
  VIX: ["SP500", "HY_SPREAD", "PUT_CALL"],
  SP500: ["VIX", "NASDAQ", "US_10Y"],
  DOW: ["SP500", "NASDAQ", "VIX"],
  NASDAQ: ["SP500", "DOW", "VIX"],
  FTSE100: ["SP500", "NIKKEI", "OIL_BRT"],
  NIKKEI: ["SP500", "FTSE100", "DXY"],
  OIL_WTI: ["CPI_YOY", "OIL_BRT", "SP500"],
  OIL_BRT: ["OIL_WTI", "CPI_YOY", "DXY"],
  GOLD: ["DXY", "VIX", "US_10Y"],
  COPPER: ["ISM_MFG", "SP500", "DXY"],
  DXY: ["GOLD", "SP500", "US_10Y"],
  PUT_CALL: ["VIX", "SP500", "HY_SPREAD"],
};

export const INDICATOR_GLOSSARY: Record<string, string> = {
  FED_FUNDS: "The interest rate banks charge each other overnight, set by the Federal Reserve.",
  US_2Y: "Yield on 2-year US Treasury bonds. Reflects expectations for Fed policy.",
  US_10Y: "Yield on 10-year Treasuries. Key benchmark for mortgages and corporate bonds.",
  US_30Y: "Yield on 30-year Treasuries. Reflects long-term inflation expectations.",
  SPREAD_2S10S: "Difference between 10Y and 2Y yields. Negative (inverted) = recession signal.",
  CPI_YOY: "Consumer Price Index year-over-year. Measures headline inflation.",
  CORE_CPI_YOY: "CPI excluding food & energy. Shows underlying inflation trend.",
  CORE_PCE_YOY: "Personal Consumption Expenditures ex food & energy. Fed's preferred inflation gauge.",
  UNEMPLOYMENT: "Percentage of labor force actively seeking work. Key economic health indicator.",
  INITIAL_CLAIMS: "Weekly new unemployment insurance filings. Early labor market warning signal.",
  NFP: "Monthly change in US non-farm employment. Most-watched jobs report.",
  ISM_MFG: "Manufacturing purchasing managers survey. Above 50 = expansion, below = contraction.",
  CONSUMER_CONF: "University of Michigan household sentiment survey. Drives spending expectations.",
  IG_SPREAD: "Extra yield on investment-grade corporate bonds over Treasuries. Measures credit risk.",
  HY_SPREAD: "Extra yield on high-yield (junk) bonds over Treasuries. Spikes during stress.",
  VIX: "Implied volatility of S&P 500 options. The 'fear index' \u2014 spikes during panic.",
  SP500: "Market-cap weighted index of 500 largest US companies. Primary US equity benchmark.",
  DOW: "Price-weighted index of 30 large US blue-chip stocks.",
  NASDAQ: "Tech-heavy index. Proxy for growth and technology sentiment.",
  FTSE100: "100 largest UK-listed companies. UK equity benchmark.",
  NIKKEI: "225 major Japanese companies. Reflects Asian sentiment and yen dynamics.",
  OIL_WTI: "West Texas Intermediate crude. US oil benchmark affecting inflation and energy stocks.",
  OIL_BRT: "Brent crude. Global oil benchmark for international pricing.",
  GOLD: "Price per ounce. Safe-haven asset rising during inflation and uncertainty.",
  COPPER: "Dr. Copper \u2014 demand reflects global industrial activity and growth.",
  DXY: "US Dollar vs 6 major currencies. Strong dollar hurts exports and emerging markets.",
  PUT_CALL: "Ratio of put to call options. High = fear; extreme readings are contrarian signals.",
};

export const FRED_LOOKBACK_YEARS = 2;
